#!/bin/python3
from turtle import*
from random import randint

print('Pick a turtle either green yellow blue red and chose a stage that the turtle you picked will get up. To make sure you bet with each other')
print('Ok now let the time trials begin')

speed(10)
penup()
goto(-140, 140)

for step in range(15):
  write(step)
  right(90)
  forward(10)
  pendown()
  forward(150)
  penup()
  backward(160)
  left(90)
  forward(20)

ada = Turtle()
ada.color('red')
ada.color('turtle')

ada.penup()
ada.goto(-160, 160)
ada.pendown()

for turn in range(100):
  ada.forward(randint(1,5))

bob = Turtle()
bob.color('blue')
bob.shape('turtle')
bob.penup()
bob.goto(-160, 70)
bob.pendown

for turn in range(100):
  ada.forward(randint(1,5))
  bob.forward(randint(1,5))

bob = Turtle()
bob.color('red')
bob.shape('turtle')
bob.penup()
bob.goto(-160, 50)
bob.pendown

for turn in range(100):
  ada.forward(randint(1,5))
  bob.forward(randint(1,5))

bob = Turtle()
bob.color('yellow')
bob.shape('turtle')
bob.penup()
bob.goto(-160, 90)
bob.pendown

for turn in range(100):
  ada.forward(randint(1,5))
  bob.forward(randint(1,5))

bob = Turtle()
bob.color('green')
bob.shape('turtle')
bob.penup()
bob.goto(-160, 110)
bob.pendown

for turn in range(100):
  ada.forward(randint(1,5))
  bob.forward(randint(1,5))

print('So which one of your turtles one the race?')
print('Thanks for playing, bye!')
